import "./globals.css";
import { Inter, Space_Grotesk } from "next/font/google";
import localFont from "next/font/local";

const grotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-grotesk",
});
const akira = localFont({ src: "./fonts/akira.otf", variable: "--font-akira" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${akira.variable} ${grotesk.variable}`}>
        {children}
      </body>
    </html>
  );
}
